apiVersion: v1
kind: Service
metadata:
  name: ib-gateway-api
  labels:
    app: ib-gateway-api
spec:
  ports:
  - port: 4003
  selector:
    app: ib
    tier: gateway
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ib-gateway-vnc
  labels:
    app: ib-gateway-vnc
spec:
  ports:
  - port: 5900
  selector:
    app: ib
    tier: gateway
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ib-gateway
  labels:
    app: ib
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ib
        tier: gateway
    spec:
      containers:
      - image: gchevalley/com-stouffcapital-ibgateway
        name: ib-gateway
        env:
        - name: VNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ibgateway
              key: vnc-password
        ports:
        - containerPort: 5900
          name: vnc
        - containerPort: 4003
          name: api
